Repository Gooaein/GoojilGoojil-BE, pull requests merged in 2024-09, with the labels that each got.

#6 ⚙ Setting - CICD 파이프라인 구축
  .github/workflows/cicd.yml
  Jenkinsfile
Labels: ⚙ Setting

#9 ✨Feature/#8 STOMP를 사용하는 웹소켓 기반의 서비스 구현
  src/main/java/com/gooaein/goojilgoojil/config/WebSocketConfig.java
  src/main/java/com/gooaein/goojilgoojil/constants/Constants.java
  src/main/java/com/gooaein/goojilgoojil/controller/GuestController.java
  src/main/java/com/gooaein/goojilgoojil/controller/QuestionController.java
  src/main/java/com/gooaein/goojilgoojil/controller/RoomController.java
  src/main/java/com/gooaein/goojilgoojil/controller/WebSocketEventListener.java
  src/main/java/com/gooaein/goojilgoojil/domain/Guest.java
  src/main/java/com/gooaein/goojilgoojil/domain/Like.java
  src/main/java/com/gooaein/goojilgoojil/domain/Review.java
  src/main/java/com/gooaein/goojilgoojil/domain/Room.java
  src/main/java/com/gooaein/goojilgoojil/domain/User.java
  src/main/java/com/gooaein/goojilgoojil/domain/nosql/Question.java
  src/main/java/com/gooaein/goojilgoojil/dto/global/ResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/EndRoomRequestDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/EnterRoomRequestDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/QuestionRequestDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/EndRoomResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/QuestionResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/ReviewDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/RoomInOutResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/exception/ErrorCode.java
  src/main/java/com/gooaein/goojilgoojil/exception/WebSocketExceptionHandler.java
  src/main/java/com/gooaein/goojilgoojil/intercepter/pre/CustomHandshakeInterceptor.java
  src/main/java/com/gooaein/goojilgoojil/repository/GuestRepository.java
  src/main/java/com/gooaein/goojilgoojil/repository/LikeRepository.java
  src/main/java/com/gooaein/goojilgoojil/repository/QuestionRepository.java
  src/main/java/com/gooaein/goojilgoojil/repository/RoomRepository.java
  src/main/java/com/gooaein/goojilgoojil/repository/UserRepository.java
  src/main/java/com/gooaein/goojilgoojil/service/GuestService.java
  src/main/java/com/gooaein/goojilgoojil/service/QuestionService.java
  src/main/java/com/gooaein/goojilgoojil/service/RoomService.java
  src/main/java/com/gooaein/goojilgoojil/service/UserService.java
  src/main/java/com/gooaein/goojilgoojil/utility/JwtUtil.java
Labels: ✨ Feature, 👦🏻동겸

#11 ✨Feature/#10 Redis와 RabbitMQ를 이용한 공감하기 중복 및 동시성 문제 해결
  build.gradle
  src/main/java/com/gooaein/goojilgoojil/config/RabbitMQConfig.java
  src/main/java/com/gooaein/goojilgoojil/controller/webSocket/WebSocketEventListener.java
  src/main/java/com/gooaein/goojilgoojil/domain/Like.java
  src/main/java/com/gooaein/goojilgoojil/domain/nosql/Question.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/LikeRequestDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/QuestionResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/service/QuestionService.java
  src/main/java/com/gooaein/goojilgoojil/service/rabbitMQ/LikeConsumerService.java
Labels: ✨ Feature, 👦🏻동겸

#13 ✨Feature/#3 아바타 생성 API / 방에 입장한 게스트 전체조회 API
  src/main/java/com/gooaein/goojilgoojil/constants/Constants.java
  src/main/java/com/gooaein/goojilgoojil/controller/GuestController.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/AvatarRequestDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/GuestResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/repository/GuestRepository.java
  src/main/java/com/gooaein/goojilgoojil/service/GuestService.java
  src/main/java/com/gooaein/goojilgoojil/utility/JwtUtil.java
Labels: ✨ Feature, 🙆🏻‍♂️정준

#17 ✨Feature/#16 강의실 상세보기 API 구현 및 각종 버그 수정
  src/main/java/com/gooaein/goojilgoojil/constants/Constants.java
  src/main/java/com/gooaein/goojilgoojil/controller/RoomController.java
  src/main/java/com/gooaein/goojilgoojil/domain/Room.java
  src/main/java/com/gooaein/goojilgoojil/dto/global/ExceptionDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/RoomDto.java
  src/main/java/com/gooaein/goojilgoojil/intercepter/pre/CustomHandshakeInterceptor.java
  src/main/java/com/gooaein/goojilgoojil/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/gooaein/goojilgoojil/security/info/AuthenticationResponse.java
  src/main/java/com/gooaein/goojilgoojil/service/RoomService.java
  src/main/java/com/gooaein/goojilgoojil/utility/CookieUtil.java
Labels: ✨ Feature, 🐞 BugFix, 👦🏻동겸

#22 🔨Refactor/#21 주석 추가, 불필요 코드 삭제, 예외처리, 쿠키 SameSite 설정 변경
  src/main/java/com/gooaein/goojilgoojil/controller/AuthController.java
  src/main/java/com/gooaein/goojilgoojil/controller/GuestController.java
  src/main/java/com/gooaein/goojilgoojil/controller/QuestionController.java
  src/main/java/com/gooaein/goojilgoojil/controller/RoomController.java
  src/main/java/com/gooaein/goojilgoojil/controller/webSocket/WebSocketEventListener.java
  src/main/java/com/gooaein/goojilgoojil/domain/Review.java
  src/main/java/com/gooaein/goojilgoojil/domain/nosql/Question.java
  src/main/java/com/gooaein/goojilgoojil/dto/global/ResponseDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/EnterRoomRequestDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/request/RoomDto.java
  src/main/java/com/gooaein/goojilgoojil/dto/response/ReviewDto.java
  src/main/java/com/gooaein/goojilgoojil/exception/ErrorCode.java
  src/main/java/com/gooaein/goojilgoojil/service/AuthService.java
  src/main/java/com/gooaein/goojilgoojil/service/GuestService.java
  src/main/java/com/gooaein/goojilgoojil/service/QuestionService.java
  src/main/java/com/gooaein/goojilgoojil/service/ReviewService.java
  src/main/java/com/gooaein/goojilgoojil/service/RoomService.java
  src/main/java/com/gooaein/goojilgoojil/service/rabbitMQ/LikeConsumerService.java
  src/main/java/com/gooaein/goojilgoojil/utility/CookieUtil.java
Labels: 🔨 Refactor, 👦🏻동겸
